version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
  web:
    build: .
    volumes:
      - .:/code
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplekey123
      - ALLOWED_HOSTS=127.0.0.1
    depends_on:
      - db
  
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8081:8081"
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
